const { Pool } = require('pg');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '.env') });

const poolString = process.env.DATABASE_URL
  ? process.env.DATABASE_URL.replace('insighted_esf7', 'insightEd')
  : `postgresql://${process.env.DB_USER}:${process.env.DB_PASSWORD}@${process.env.DB_HOST}:${process.env.DB_PORT}/insightEd`;

const pool = new Pool({
  connectionString: poolString,
  ssl: process.env.DB_SSL === 'true' ? { rejectUnauthorized: false } : false
});

async function createAndSeedDummyDatabase() {
  try {
    console.log('--- Ensuring table esf7_database_dummy exists ---');
    await pool.query(`
      CREATE TABLE IF NOT EXISTS esf7_database_dummy (LIKE esf7_database INCLUDING ALL);
    `);
    console.log('✓ Table esf7_database_dummy ready.');

    // Clear existing 199998 and 199997 rows in dummy database
    await pool.query(`DELETE FROM esf7_database_dummy WHERE CAST(schoool_id AS TEXT) IN ('199998', '199997')`);

    console.log('--- Seeding realistic DepEd dummy personnel for Schools 199998 and 199997 ---');

    const dummyPersonnel = [
      {
        schoool_id: '199998',
        school_name: 'ORIENTATION DEMONSTRATION INTEGRATED SCHOOL',
        region: 'REGION V',
        division: 'LEGASPI CITY',
        muncipality: 'ALBAY II DISTRICT',
        district: 'ALBAY II DISTRICT',
        employee_no: '4109281',
        first: 'MARIA SANTOS',
        middle: 'CRUZ',
        last: 'DELA CRUZ',
        tin: '123-456-789',
        gender: 'FEMALE',
        civil_status: 'MARRIED',
        religion: 'ROMAN CATHOLIC',
        ehtinic_group: 'TAGALOG',
        birthday_yyyy: '1978',
        birthday_mm: '05',
        birthday_dd: '14',
        position: 'SCHOOL PRINCIPAL II',
        degree_finished__baccalaureate: 'BACHELOR OF SECONDARY EDUCATION',
        major__specialization: 'EDUCATIONAL MANAGEMENT',
        post_graduate__degree: 'DOCTOR OF EDUCATION (ED.D.)',
        eligibility: 'PRINCIPALS TEST / LET',
        fund_source: 'NATIONAL',
        nature_of_appointment: 'REGULAR PERMANENT',
        hiring_arrangement: 'REGULAR/PERMANENT',
        appt_yyyy: '2001',
        appt_mm: '06',
        appt_dd: '01'
      },
      {
        schoool_id: '199998',
        school_name: 'ORIENTATION DEMONSTRATION INTEGRATED SCHOOL',
        region: 'REGION V',
        division: 'LEGASPI CITY',
        muncipality: 'ALBAY II DISTRICT',
        district: 'ALBAY II DISTRICT',
        employee_no: '4250732',
        first: 'JUAN MANUEL',
        middle: 'REYES',
        last: 'PEREZ',
        tin: '234-567-890',
        gender: 'MALE',
        civil_status: 'MARRIED',
        religion: 'ROMAN CATHOLIC',
        ehtinic_group: 'TAGALOG',
        birthday_yyyy: '1983',
        birthday_mm: '08',
        birthday_dd: '22',
        position: 'MASTER TEACHER I',
        degree_finished__baccalaureate: 'BACHELOR OF SECONDARY EDUCATION',
        major__specialization: 'MATHEMATICS',
        post_graduate__degree: 'MASTER OF ARTS IN EDUCATION (MAED)',
        eligibility: 'LICENSURE EXAMINATION FOR TEACHERS',
        fund_source: 'NATIONAL',
        nature_of_appointment: 'REGULAR PERMANENT',
        hiring_arrangement: 'REGULAR/PERMANENT',
        appt_yyyy: '2006',
        appt_mm: '06',
        appt_dd: '15',
        subject_1: 'MATHEMATICS 7',
        lvl_1: 'Grade 7',
        section_1: 'DIAMOND',
        from_1: '07:30',
        to_1: '08:30',
        d1_1: 'M', d2_1: 'T', d3_1: 'W', d4_1: 'TH', d5_1: 'F',
        subject_1_2: 'MATHEMATICS 8',
        lvl_1_2: 'Grade 8',
        section_1_2: 'EMERALD',
        from_1_2: '08:30',
        to_1_2: '09:30',
        d1_1_2: 'M', d2_1_2: 'T', d3_1_2: 'W', d4_1_2: 'TH', d5_1_2: 'F',
        subject_1_3: 'HOMEROOM GUIDANCE (HGP)',
        lvl_1_3: 'Grade 7',
        section_1_3: 'DIAMOND',
        from_1_3: '09:45',
        to_1_3: '10:45',
        d1_1_3: 'M', d2_1_3: 'T', d3_1_3: 'W', d4_1_3: 'TH', d5_1_3: 'F',
        subject_1_4: 'ADVISORY CLASS',
        lvl_1_4: 'Grade 7',
        section_1_4: 'DIAMOND',
        from_1_4: '09:45',
        to_1_4: '10:45',
        d1_1_4: 'M', d2_1_4: 'T', d3_1_4: 'W', d4_1_4: 'TH', d5_1_4: 'F'
      },
      {
        schoool_id: '199998',
        school_name: 'ORIENTATION DEMONSTRATION INTEGRATED SCHOOL',
        region: 'REGION V',
        division: 'LEGASPI CITY',
        muncipality: 'ALBAY II DISTRICT',
        district: 'ALBAY II DISTRICT',
        employee_no: '4391823',
        first: 'ANA MARIE',
        middle: 'GARCIA',
        last: 'VILLANUEVA',
        tin: '345-678-901',
        gender: 'FEMALE',
        civil_status: 'SINGLE',
        religion: 'CHRISTIANITY',
        ehtinic_group: 'BICOLANO',
        birthday_yyyy: '1990',
        birthday_mm: '11',
        birthday_dd: '03',
        position: 'TEACHER III',
        degree_finished__baccalaureate: 'BACHELOR OF SECONDARY EDUCATION',
        major__specialization: 'GENERAL SCIENCE',
        post_graduate__degree: 'CAR - MASTER OF ARTS IN TEACHING',
        eligibility: 'LICENSURE EXAMINATION FOR TEACHERS',
        fund_source: 'NATIONAL',
        nature_of_appointment: 'REGULAR PERMANENT',
        hiring_arrangement: 'REGULAR/PERMANENT',
        appt_yyyy: '2014',
        appt_mm: '07',
        appt_dd: '01',
        subject_1: 'SCIENCE 9',
        lvl_1: 'Grade 9',
        section_1: 'RUBY',
        from_1: '07:30',
        to_1: '08:30',
        d1_1: 'M', d2_1: 'T', d3_1: 'W', d4_1: 'TH', d5_1: 'F',
        subject_1_2: 'SCIENCE 10',
        lvl_1_2: 'Grade 10',
        section_1_2: 'SAPPHIRE',
        from_1_2: '08:30',
        to_1_2: '09:30',
        d1_1_2: 'M', d2_1_2: 'T', d3_1_2: 'W', d4_1_2: 'TH', d5_1_2: 'F',
        subject_1_3: 'SCIENCE 9',
        lvl_1_3: 'Grade 9',
        section_1_3: 'PEARL',
        from_1_3: '09:45',
        to_1_3: '10:45',
        d1_1_3: 'M', d2_1_3: 'T', d3_1_3: 'W', d4_1_3: 'TH', d5_1_3: 'F',
        subject_1_4: 'RESEARCH II',
        lvl_1_4: 'Grade 10',
        section_1_4: 'SAPPHIRE',
        from_1_4: '10:45',
        to_1_4: '11:45',
        d1_1_4: 'M', d2_1_4: 'T', d3_1_4: 'W', d4_1_4: 'TH', d5_1_4: 'F',
        subject_1_5: 'SCIENCE 8',
        lvl_1_5: 'Grade 8',
        section_1_5: 'TOPAZ',
        from_1_5: '13:00',
        to_1_5: '14:00',
        d1_1_5: 'M', d2_1_5: 'T', d3_1_5: 'W', d4_1_5: 'TH', d5_1_5: 'F',
        subject_1_6: 'SCIENCE 8',
        lvl_1_6: 'Grade 8',
        section_1_6: 'JADE',
        from_1_6: '14:00',
        to_1_6: '15:00',
        d1_1_6: 'M', d2_1_6: 'T', d3_1_6: 'W', d4_1_6: 'TH', d5_1_6: 'F',
        subject_1_7: 'SPECIAL SCIENCE EXTRA PERIOD',
        lvl_1_7: 'Grade 10',
        section_1_7: 'SAPPHIRE',
        from_1_7: '15:00',
        to_1_7: '16:00',
        d1_1_7: 'M', d2_1_7: 'T', d3_1_7: 'W', d4_1_7: 'TH', d5_1_7: 'F'
      },
      {
        schoool_id: '199998',
        school_name: 'ORIENTATION DEMONSTRATION INTEGRATED SCHOOL',
        region: 'REGION V',
        division: 'LEGASPI CITY',
        muncipality: 'ALBAY II DISTRICT',
        district: 'ALBAY II DISTRICT',
        employee_no: '',
        first: 'ROBERTO CARLOS',
        middle: 'SANTOS',
        last: 'GARCIA',
        tin: '456-789-012',
        gender: 'MALE',
        civil_status: 'SINGLE',
        religion: 'ROMAN CATHOLIC',
        ehtinic_group: 'BICOLANO',
        birthday_yyyy: '1996',
        birthday_mm: '04',
        birthday_dd: '19',
        position: 'TEACHER I',
        degree_finished__baccalaureate: 'BACHELOR OF SECONDARY EDUCATION',
        major__specialization: 'ENGLISH',
        post_graduate__degree: 'N/A',
        eligibility: 'LICENSURE EXAMINATION FOR TEACHERS',
        fund_source: 'NATIONAL',
        nature_of_appointment: 'PROVISIONAL',
        hiring_arrangement: 'PROVISIONAL',
        appt_yyyy: '2022',
        appt_mm: '08',
        appt_dd: '22',
        subject_1: 'ENGLISH 7',
        lvl_1: 'Grade 7',
        section_1: 'DIAMOND',
        from_1: '08:30',
        to_1: '09:30',
        d1_1: 'M', d2_1: 'T', d3_1: 'W', d4_1: 'TH', d5_1: 'F',
        subject_1_2: 'ENGLISH 8',
        lvl_1_2: 'Grade 8',
        section_1_2: 'EMERALD',
        from_1_2: '09:45',
        to_1_2: '10:45',
        d1_1_2: 'M', d2_1_2: 'T', d3_1_2: 'W', d4_1_2: 'TH', d5_1_2: 'F',
        subject_1_3: 'ENGLISH 9',
        lvl_1_3: 'Grade 9',
        section_1_3: 'RUBY',
        from_1_3: '10:45',
        to_1_3: '11:45',
        d1_1_3: 'M', d2_1_3: 'T', d3_1_3: 'W', d4_1_3: 'TH', d5_1_3: 'F',
        subject_1_4: 'ENGLISH 10',
        lvl_1_4: 'Grade 10',
        section_1_4: 'SAPPHIRE',
        from_1_4: '13:00',
        to_1_4: '14:00',
        d1_1_4: 'M', d2_1_4: 'T', d3_1_4: 'W', d4_1_4: 'TH', d5_1_4: 'F'
      },
      {
        schoool_id: '199998',
        school_name: 'ORIENTATION DEMONSTRATION INTEGRATED SCHOOL',
        region: 'REGION V',
        division: 'LEGASPI CITY',
        muncipality: 'ALBAY II DISTRICT',
        district: 'ALBAY II DISTRICT',
        employee_no: '4512903',
        first: 'ELENA JOYCE',
        middle: 'LOPEZ',
        last: 'RAMOS',
        tin: '567-890-123',
        gender: 'FEMALE',
        civil_status: 'MARRIED',
        religion: 'ROMAN CATHOLIC',
        ehtinic_group: 'TAGALOG',
        birthday_yyyy: '1992',
        birthday_mm: '09',
        birthday_dd: '28',
        position: 'TEACHER II',
        degree_finished__baccalaureate: 'BACHELOR OF ELEMENTARY EDUCATION',
        major__specialization: 'ARALING PANLIPUNAN',
        post_graduate__degree: 'N/A',
        eligibility: 'LICENSURE EXAMINATION FOR TEACHERS',
        fund_source: 'NATIONAL',
        nature_of_appointment: 'REGULAR PERMANENT',
        hiring_arrangement: 'REGULAR/PERMANENT',
        appt_yyyy: '2017',
        appt_mm: '06',
        appt_dd: '05',
        subject_1: 'ARALING PANLIPUNAN 5',
        lvl_1: 'Grade 5',
        section_1: 'MASIGLA',
        from_1: '07:30',
        to_1: '08:30',
        d1_1: 'M', d2_1: 'T', d3_1: 'W', d4_1: 'TH', d5_1: 'F',
        subject_1_2: 'ARALING PANLIPUNAN 6',
        lvl_1_2: 'Grade 6',
        section_1_2: 'MATATAG',
        from_1_2: '08:30',
        to_1_2: '09:30',
        d1_1_2: 'M', d2_1_2: 'T', d3_1_2: 'W', d4_1_2: 'TH', d5_1_2: 'F'
      },
      {
        schoool_id: '199998',
        school_name: 'ORIENTATION DEMONSTRATION INTEGRATED SCHOOL',
        region: 'REGION V',
        division: 'LEGASPI CITY',
        muncipality: 'ALBAY II DISTRICT',
        district: 'ALBAY II DISTRICT',
        employee_no: '4623812',
        first: 'MARK ANTHONY',
        middle: 'VALDEZ',
        last: 'DIZON',
        tin: '678-901-234',
        gender: 'MALE',
        civil_status: 'MARRIED',
        religion: 'EVANGELICAL',
        ehtinic_group: 'BICOLANO',
        birthday_yyyy: '1985',
        birthday_mm: '12',
        birthday_dd: '10',
        position: 'HEAD TEACHER III',
        degree_finished__baccalaureate: 'BACHELOR OF SECONDARY EDUCATION',
        major__specialization: 'FILIPINO',
        post_graduate__degree: 'MASTER OF ARTS IN FILIPINO',
        eligibility: 'LICENSURE EXAMINATION FOR TEACHERS',
        fund_source: 'NATIONAL',
        nature_of_appointment: 'REGULAR PERMANENT',
        hiring_arrangement: 'REGULAR/PERMANENT',
        appt_yyyy: '2009',
        appt_mm: '06',
        appt_dd: '01',
        subject_1: 'FILIPINO 10',
        lvl_1: 'Grade 10',
        section_1: 'SAPPHIRE',
        from_1: '07:30',
        to_1: '08:30',
        d1_1: 'M', d2_1: 'T', d3_1: 'W', d4_1: 'TH', d5_1: 'F',
        subject_1_2: 'TR - DEPARTMENT HEAD (INSTRUCTIONAL SUPERVISION)',
        lvl_1_2: 'Grade 10',
        section_1_2: 'ALL',
        from_1_2: '08:30',
        to_1_2: '11:30',
        d1_1_2: 'M', d2_1_2: 'T', d3_1_2: 'W', d4_1_2: 'TH', d5_1_2: 'F'
      },
      {
        schoool_id: '199998',
        school_name: 'ORIENTATION DEMONSTRATION INTEGRATED SCHOOL',
        region: 'REGION V',
        division: 'LEGASPI CITY',
        muncipality: 'ALBAY II DISTRICT',
        district: 'ALBAY II DISTRICT',
        employee_no: '4789012',
        first: 'CLARISSA MAE',
        middle: 'BELTRAN',
        last: 'SORIANO',
        tin: '789-012-345',
        gender: 'FEMALE',
        civil_status: 'SINGLE',
        religion: 'ROMAN CATHOLIC',
        ehtinic_group: 'TAGALOG',
        birthday_yyyy: '1994',
        birthday_mm: '03',
        birthday_dd: '17',
        position: 'ADMINISTRATIVE OFFICER II',
        degree_finished__baccalaureate: 'BACHELOR OF SCIENCE IN BUSINESS ADMINISTRATION',
        major__specialization: 'FINANCIAL MANAGEMENT',
        post_graduate__degree: 'N/A',
        eligibility: 'CAREER SERVICE PROFESSIONAL',
        fund_source: 'NATIONAL',
        nature_of_appointment: 'REGULAR PERMANENT',
        hiring_arrangement: 'REGULAR/PERMANENT',
        appt_yyyy: '2019',
        appt_mm: '10',
        appt_dd: '01'
      },
      {
        schoool_id: '199998',
        school_name: 'ORIENTATION DEMONSTRATION INTEGRATED SCHOOL',
        region: 'REGION V',
        division: 'LEGASPI CITY',
        muncipality: 'ALBAY II DISTRICT',
        district: 'ALBAY II DISTRICT',
        employee_no: '',
        first: 'EDUARDO RAMON',
        middle: 'FLORES',
        last: 'BAUTISTA',
        tin: '890-123-456',
        gender: 'MALE',
        civil_status: 'MARRIED',
        religion: 'ROMAN CATHOLIC',
        ehtinic_group: 'BICOLANO',
        birthday_yyyy: '1988',
        birthday_mm: '07',
        birthday_dd: '25',
        position: 'UTILITY WORKER I',
        degree_finished__baccalaureate: 'HIGH SCHOOL GRADUATE',
        major__specialization: 'GENERAL EDUCATION',
        post_graduate__degree: 'N/A',
        eligibility: 'NONE',
        fund_source: 'MOOE',
        nature_of_appointment: 'CONTRACT OF SERVICE / JOB ORDER',
        hiring_arrangement: 'CONTRACTUAL / JOB ORDER',
        appt_yyyy: '2023',
        appt_mm: '01',
        appt_dd: '16'
      },
      // ── PARTNER DEMO SATELLITE SCHOOL 199997 ──────────────────────────────────
      {
        schoool_id: '199997',
        school_name: 'ORIENTATION SATELLITE ELEMENTARY SCHOOL',
        region: 'REGION V',
        division: 'LEGASPI CITY',
        muncipality: 'ALBAY II DISTRICT',
        district: 'ALBAY II DISTRICT',
        employee_no: '4890123',
        first: 'GABRIEL',
        middle: 'CRUZ',
        last: 'DELOS REYES',
        tin: '901-234-567',
        gender: 'MALE',
        civil_status: 'MARRIED',
        religion: 'ROMAN CATHOLIC',
        ehtinic_group: 'TAGALOG',
        birthday_yyyy: '1980',
        birthday_mm: '02',
        birthday_dd: '11',
        position: 'SCHOOL PRINCIPAL I',
        degree_finished__baccalaureate: 'BACHELOR OF ELEMENTARY EDUCATION',
        major__specialization: 'EDUCATIONAL ADMINISTRATION',
        post_graduate__degree: 'MASTER OF ARTS IN EDUCATION',
        eligibility: 'PRINCIPALS TEST / LET',
        fund_source: 'NATIONAL',
        nature_of_appointment: 'REGULAR PERMANENT',
        hiring_arrangement: 'REGULAR/PERMANENT',
        appt_yyyy: '2004',
        appt_mm: '06',
        appt_dd: '01'
      },
      {
        schoool_id: '199997',
        school_name: 'ORIENTATION SATELLITE ELEMENTARY SCHOOL',
        region: 'REGION V',
        division: 'LEGASPI CITY',
        muncipality: 'ALBAY II DISTRICT',
        district: 'ALBAY II DISTRICT',
        employee_no: '4901234',
        first: 'TERESA',
        middle: 'SANTOS',
        last: 'AQUINO',
        tin: '012-345-678',
        gender: 'FEMALE',
        civil_status: 'SINGLE',
        religion: 'ROMAN CATHOLIC',
        ehtinic_group: 'BICOLANO',
        birthday_yyyy: '1993',
        birthday_mm: '06',
        birthday_dd: '18',
        position: 'TEACHER I',
        degree_finished__baccalaureate: 'BACHELOR OF ELEMENTARY EDUCATION',
        major__specialization: 'GENERAL EDUCATION',
        post_graduate__degree: 'N/A',
        eligibility: 'LICENSURE EXAMINATION FOR TEACHERS',
        fund_source: 'NATIONAL',
        nature_of_appointment: 'REGULAR PERMANENT',
        hiring_arrangement: 'REGULAR/PERMANENT',
        appt_yyyy: '2018',
        appt_mm: '06',
        appt_dd: '04',
        subject_1: 'MATHEMATICS 3',
        lvl_1: 'Grade 3',
        section_1: 'SAMPAGUITA',
        from_1: '07:30',
        to_1: '08:30',
        d1_1: 'M', d2_1: 'T', d3_1: 'W', d4_1: 'TH', d5_1: 'F'
      }
    ];

    for (const p of dummyPersonnel) {
      const keys = Object.keys(p);
      const values = Object.values(p);
      const placeholders = values.map((_, i) => `$${i + 1}`).join(', ');
      const colNames = keys.map(k => `"${k}"`).join(', ');

      await pool.query(
        `INSERT INTO esf7_database_dummy (${colNames}) VALUES (${placeholders})`,
        values
      );
      console.log(`  + Inserted: ${p.first} ${p.last} (${p.position})`);
    }

    console.log('\n🎉 SUCCESS: esf7_database_dummy created and 8 dummy personnel seeded for School 199998!');
  } catch (err) {
    console.error('Error during creation/seeding:', err);
  } finally {
    await pool.end();
  }
}

createAndSeedDummyDatabase();
